services:
  stump:
    image: aaronleopold/stump:${VERSION:-latest}
    container_name: stump
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - ${PORT:-10801}:10801
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
